version: '3.1'
services:
        database:
                build:
                        context: .
                        dockerfile: Mysql
                volumes:
                        - "./data:/var/lib/mysql"
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: pieski
                        MYSQL_USER: ewa
                        MYSQL_PASSWORD: ewa
                networks:
                        - backend
        phpmyadmin:
                build: 
                        context: .
                        dockerfile: Phpmyadmin
                depends_on: 
                        - database
                ports: 
                        - '8080:80'
                environment:
                        PMA_HOST: database
                        MYSQL_ROOT_PASSWORD: password
                networks:
                        - backend
        php_apache_7.4:
                build: 
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 6666:80/tcp
                volumes:
                        - "./DocumentRoot:/var/www/html"
                networks: 
                        - backend
                        - frontend
networks:
        frontend:
        backend:
volumes: 
        data:
